### PR TITLE
Feature/post hwt 2

### PR DESCRIPTION
**Pull request by EdwardColon-NOAA**
Second attempt. I accidentally pulled from the incorrect branch, previously.

### CODE REVIEW

**Review by guoqing-noaa — COMMENTED** [review]
1. ush/checkout_rtma_gsi.sh:
    Line 109: echo " ====> git clone gerrit:ProdGSI  ./${DIRNAME_GSI} "
   You may want to change gerrit to github accordingly here.

2. The following files don't need to be tracked in Github:
workflow/run_rtma3d_lsf_subhr.log 
workflow/run_rtma3d_lsf.log
workflow/rtma3d_lsf_retro.xml
Other .xml, .db, .db_lock files

I think the above files were committed accidentally and it is because current .gitignore in the develop and related branches does not work. I will submit a new working .gitignore from a jet/* branch through a PR after this is merged.

**Review by GangZhao-NOAA — APPROVED** [review]
Hi Ed,

As Guoqing pointed out, there are a few files ( 7 files) which should not be included:
1. log files 
    workflow/run_rtma3d_lsf.log, 
    workflow/run_rtma3d_lsf_retro.log, 
    workflow/run_rtma3d_lsf_subhr.log)
2. db files: 
    workflow/rtma3d_lsf_lock.db,
    workflow/rtma3d_lsf.db
    workflow/.db_lock          (be careful with this! It might be a hidden file since it is "dot" file.)
3. back up file:
    workflow/chk_rtma3d_lsf.sh_back

Except for those files, I think it should be OK to merge these changes.

But it is OK even you keep these files in the pull request. As Guoqing said, you can delete them later after this merge. So I approve for this pull request.

Another concern is about the those "check-out" and "build" scripts. It is my bad to introduce these scripts into system. Actually they could be replaced by a well-maintained "ReadMe" file or something like it. Keeping those scripts might cause more unnecessary work for you in the future. But we can discuss this issue in next step.

Approve.

Thank you!

Gang

**Comment by EdwardColon-NOAA** [comment]
Hi Guoqing and Gang,

I believe that I've removed the extraneous files from the workflow directory. In renaming the directory from xml to workflow, the commit likely added these files by accident. Currently, only three prep scripts should exist in the workflow directory - one for retro experiments, one for real-time, and an old prep script that I had working on jet some time ago.

-Edward

**Review by guoqing-noaa — APPROVED** [review]
Edward, it looks good to me. Thanks!

**Pull request merged**
